name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          # - windows-latest
        raku-version:
          - "2021.07"
          - "latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Libraries (MacOS)
        if: matrix.os == 'macOS-latest'
        run: brew install openssl
      - name: Setup dependencies
        run: raku -v && zef install --verbose --deps-only .
      - name: Test code
        run: zef test .
